{% set package = load_file_data('Cargo.toml').get('package', {}) %}
{% set name = package.get("name") %}
{% set version = package.get("version") %}
{% set description = package.get("description") %}
{% set homepage = package.get("homepage") %}
{% set dev_url = package.get("repository") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  fn: "{{ name }}-{{ version }}.tar.gz"
  sha256: 5be60026f0feda893b91461628dcb0a4aad68dc8f2f35bf6618f68587f0807aa

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: {{ homepage }}
  dev_url: {{ dev_url }}
  summary: 'Submit slurm sbatch jobs without a script'
  description: {{ description }}
  license: Unlicense
  license_file: 
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - mbhall88
