{% set name = "ssubmit" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  fn: "{{ name }}-{{ version }}.tar.gz"
  sha256: b6c27ca251688a99aede769264cde461c086793d4d0a0e9dfda7eb62ca8d4c42

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - ssubmit --help

about:
  home: https://github.com/mbhall88/{{ name }}
  summary: 'Submit slurm sbatch jobs without a script'
  description: |
    Submit slurm sbatch jobs without a script 
  license: Unlicense
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - mbhall88
