{% set name = "ssubmit" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mbhall88/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: da6379d478b817cefce625d783f946884e035edbf1d4c11727d3f9d86756def9

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - ssubmit --help

about:
  home: https://github.com/mbhall88/{{ name }}
  summary: 'Submit slurm sbatch jobs without a script'
  description: |
    Submit slurm sbatch jobs without a script 
  license: Unlicense
  license_file: 
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - mbhall88
